artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/tejas05in/data/raw/c05fa213df0647fe44344b1ef9ae008e1eddde54/cat-dog-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion